### ISSUE TITLE
需要进一步封装

### ISSUE THREAD

**Issue by shifujun** [undefinal/newtest-ci-action#1]
```
# 随机获取设备，连接远端优测真机，然后执行script脚本
      - name: Newtest ci
        uses: undefinal/newtest-ci-action@master
        with:
          secretId: xxx
          secretKey: xxx
          getDeviceBy: random #随机获取设备
          deviceNumber: 2 #设备数
          script: adb devices -l #应该显示出已连接的设备
          
      # 按条件过滤获取设备，连接远端优测真机，然后执行script脚本
      - name: Newtest ci
        uses: undefinal/newtest-ci-action@master
        with:
          secretId: xxx
          secretKey: xxx
          getDeviceBy: condition #按条件获取设备
          brands: xxx 
          sdks: xxx
          resolutions: xxx
          ...
          aliases: xxx
          script: adb devices -l #应该显示出已连接的设备
```

希望提供如上两种使用方法。

两种方法在调用完open CGI后都会获得对应设备的端口号。假设获取了多个设备，则需要多次调用本地命令`adb connect utest.21kunpeng.com:<port>`，链接这些设备。

adb命令可以在`runs-on: macos-latest`或者`runs-on: ubuntu-latest`中使用。这两个环境已经安装了adb。在OCI中，可以测试`csighub.tencentyun.com/cubershi/ilive-sdk-android-only-sdk-tools`这个Docker镜像。

然后执行用户传入的script脚本，举例中的`adb devices -l`命令就是打印已连接设备的命令。正常CI中一般会执行`./gradlew connectedAndroidTest`这样的自动化测试脚本。

在script脚本退出后，不管是否出错，都调用Release CGI释放远端设备。

另外请考虑一下secretId和key如何在Github Actions和OCI上以兼容的安全方式传入，这里我也不太清楚，可以一起看一下。
